service: serverless-game
# app and org for use with dashboard.serverless.com
app: serverless-game
org: silarsis


custom:
  thingTableName: 'thing-table-${self:provider.stage}'
  locationTableName: 'location-table-${self:provider.stage}'
  contentsTableName: 'contents-table-${self:provider.stage}'

provider:
  name: aws
  runtime: python3.8
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["ThingDynamoDBTable", "Arn" ] }
        - { "Fn::GetAtt": ["LocationDynamoDBTable", "Arn" ] }
        - { "Fn::GetAtt": ["ContentsDynamoDBTable", "Arn" ] }
  environment:
    THING_TABLE: ${self:custom.thingTableName}
    LOCATION_TABLE: ${self:custom.locationTableName}
    CONTENTS_TABLE: ${self:custom.contentsTableName}

functions:
  thing:
    handler: mixins/thing.handler
    VpcId:
      Ref:
        Fn::ImportValue: VpcId
    package:
      exclude:
        - ./**
      include:
        - mixins/**
    events:
      - sns:
          arn: !Ref ThingTopic
          topicName: ThingTopic
  location:
    handler: mixins/location.handler
    VpcId:
      Ref:
        Fn::ImportValue: VpcId
    package:
      exclude:
        - ./**
      include:
        - mixins/**
    events:
      - sns:
          arn: !Ref ThingTopic
          topicName: ThingTopic
          filterPolicy:
            mixin: location

resources:
  Resources:
    ThingTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ThingTopic
    ThingDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: uuid
            AttributeType: S
        KeySchema:
          -
            AttributeName: uuid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.thingTableName}
    LocationDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: uuid
            AttributeType: S
        KeySchema:
          -
            AttributeName: uuid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.locationTableName}
    ContentsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: uuid
            AttributeType: S
          -
            AttributeName: contains
            AttributeType: S
        KeySchema:
          -
            AttributeName: uuid
            KeyType: HASH
          -
            AttributeName: contains
            KeyType: RANGE
        GlobalSecondaryIndexes:
          IndexName: containing
          KeySchema:
            -
              AttributeName: contains
              KeyType: RANGE
              Projection:
                ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.contentsTableName}